name: encrypt secrets

on:
  push:

jobs:
  encrypt:
    name: Encrypt AWS secrets with ENCODING_KEY
    runs-on: ubuntu-latest
    steps:
      - name: Encrypt AWS_ACCESS_KEY_ID
        env:
          MY_SECRET: ${{ secrets.AWS_ACCESS_KEY_ID }}
          ENCODING_KEY: ${{ secrets.ENCODING_KEY }}
        run: |
          ENCRYPTED=$(echo -n "$MY_SECRET" | openssl enc -aes-256-cbc -pbkdf2 -base64 -A -pass pass:"$ENCODING_KEY")
          echo "AWS_ACCESS_KEY_ID (encrypted):"
          echo "$ENCRYPTED"

      - name: Encrypt AWS_SECRET_ACCESS_KEY
        env:
          MY_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENCODING_KEY: ${{ secrets.ENCODING_KEY }}
        run: |
          ENCRYPTED=$(echo -n "$MY_SECRET" | openssl enc -aes-256-cbc -pbkdf2 -base64 -A -pass pass:"$ENCODING_KEY")
          echo "AWS_SECRET_ACCESS_KEY (encrypted):"
          echo "$ENCRYPTED"


      - name: Encrypt AWS_ROLE_TO_ASSUME
        env:
          MY_SECRET: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          ENCODING_KEY: ${{ secrets.ENCODING_KEY }}
        run: |
          ENCRYPTED=$(echo -n "$MY_SECRET" | openssl enc -aes-256-cbc -pbkdf2 -base64 -A -pass pass:"$ENCODING_KEY")
          echo "AWS_ROLE_TO_ASSUME (encrypted):"
          echo "$ENCRYPTED"
